package vakuutus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import vakuutus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.28 12:30:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AsiakkaatTest {



  // Generated by ComTest BEGIN
  /** testLisaa43 */
  @Test
  public void testLisaa43() {    // Asiakkaat: 43
    Asiakkaat asiakkaat = new Asiakkaat(); 
    Asiakas marko1 = new Asiakas(), marko2 = new Asiakas(); 
    assertEquals("From: Asiakkaat line: 46", 0, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 47", 1, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko2); assertEquals("From: Asiakkaat line: 48", 2, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 49", 3, asiakkaat.getLkm()); 
    assertEquals("From: Asiakkaat line: 50", marko1, asiakkaat.anna(0)); 
    assertEquals("From: Asiakkaat line: 51", marko2, asiakkaat.anna(1)); 
    assertEquals("From: Asiakkaat line: 52", marko1, asiakkaat.anna(2)); 
    assertEquals("From: Asiakkaat line: 53", false, asiakkaat.anna(1) == marko1); 
    assertEquals("From: Asiakkaat line: 54", true, asiakkaat.anna(1) == marko2); 
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 55", 4, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 56", 5, asiakkaat.getLkm()); 
  } // Generated by ComTest END
}