package vakuutus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import vakuutus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.21 15:02:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AsiakasTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi52 */
  @Test
  public void testRekisteroi52() {    // Asiakas: 52
    Asiakas aku1=new Asiakas(); 
    assertEquals("From: Asiakas line: 54", 0, aku1.getTunnusNro()); 
    aku1.rekisteroi(); 
    Asiakas aku2=new Asiakas(); 
    aku2.rekisteroi(); 
    int n1=aku1.getTunnusNro(); 
    int n2= aku2.getTunnusNro(); 
    assertEquals("From: Asiakas line: 61", n2-1, n1); 
    
  } // Generated by ComTest END
}