package vakuutus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import vakuutus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.13 12:07:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AsiakkaatTest {



  // Generated by ComTest BEGIN
  /** testLisaa37 */
  @Test
  public void testLisaa37() {    // Asiakkaat: 37
    Asiakkaat asiakkaat = new Asiakkaat(); 
    Asiakas marko1 = new Asiakas(), marko2 = new Asiakas(); 
    assertEquals("From: Asiakkaat line: 40", 0, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 41", 1, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko2); assertEquals("From: Asiakkaat line: 42", 2, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 43", 3, asiakkaat.getLkm()); 
    assertEquals("From: Asiakkaat line: 44", marko1, asiakkaat.anna(0)); 
    assertEquals("From: Asiakkaat line: 45", marko2, asiakkaat.anna(1)); 
    assertEquals("From: Asiakkaat line: 46", marko1, asiakkaat.anna(2)); 
    assertEquals("From: Asiakkaat line: 47", false, asiakkaat.anna(1) == marko1); 
    assertEquals("From: Asiakkaat line: 48", true, asiakkaat.anna(1) == marko2); 
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 49", 4, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 50", 5, asiakkaat.getLkm()); 
  } // Generated by ComTest END
}