package vakuutus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import vakuutus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.06 19:12:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AsiakkaatTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa28 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa28() throws SailoException {    // Asiakkaat: 28
    Asiakkaat asiakkaat = new Asiakkaat(); 
    Asiakas marko1 = new Asiakas(), marko2 = new Asiakas(); 
    assertEquals("From: Asiakkaat line: 32", 0, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 33", 1, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko2); assertEquals("From: Asiakkaat line: 34", 2, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 35", 3, asiakkaat.getLkm()); 
    assertEquals("From: Asiakkaat line: 36", marko1, asiakkaat.anna(0)); 
    assertEquals("From: Asiakkaat line: 37", marko2, asiakkaat.anna(1)); 
    assertEquals("From: Asiakkaat line: 38", marko1, asiakkaat.anna(2)); 
    assertEquals("From: Asiakkaat line: 39", false, asiakkaat.anna(1) == marko1); 
    assertEquals("From: Asiakkaat line: 40", true, asiakkaat.anna(1) == marko2); 
    try {
    assertEquals("From: Asiakkaat line: 41", marko1, asiakkaat.anna(3)); 
    fail("Asiakkaat: 41 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 42", 4, asiakkaat.getLkm()); 
    asiakkaat.lisaa(marko1); assertEquals("From: Asiakkaat line: 43", 5, asiakkaat.getLkm()); 
    try {
    asiakkaat.lisaa(marko1); 
    fail("Asiakkaat: 44 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}