package vakuutus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import vakuutus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.02.23 11:02:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AsiakasTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi72 */
  @Test
  public void testRekisteroi72() {    // Asiakas: 72
    Asiakas marko1 = new Asiakas(); 
    assertEquals("From: Asiakas line: 74", 0, marko1.getTunnusNro()); 
    marko1.rekisteroi(); 
    Asiakas marko2 = new Asiakas(); 
    marko2.rekisteroi(); 
    int n1 = marko2.getTunnusNro(); 
    int n2 = marko2.getTunnusNro(); 
    assertEquals("From: Asiakas line: 81", n2-1, n1); 
  } // Generated by ComTest END
}