package vakuutus.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import vakuutus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.13 12:44:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KotivakuutuksetTest {



  // Generated by ComTest BEGIN
  /** testAnnaKotivakuutukset84 */
  @Test
  public void testAnnaKotivakuutukset84() {    // Kotivakuutukset: 84
    Kotivakuutukset kotona = new Kotivakuutukset(); 
    Kotivakuutus koti21 = new Kotivakuutus(2); kotona.lisaa(koti21); 
    Kotivakuutus koti11 = new Kotivakuutus(4); kotona.lisaa(koti11); 
    Kotivakuutus koti22 = new Kotivakuutus(2); kotona.lisaa(koti22); 
    Kotivakuutus koti12 = new Kotivakuutus(1); kotona.lisaa(koti12); 
    Kotivakuutus koti23 = new Kotivakuutus(2); kotona.lisaa(koti23); 
    Kotivakuutus koti51 = new Kotivakuutus(5); kotona.lisaa(koti51); 
    List<Kotivakuutus> loydetyt; 
    loydetyt = kotona.annaKotivakuutukset(1); 
    assertEquals("From: Kotivakuutukset line: 97", 0, loydetyt.size()); 
    assertEquals("From: Kotivakuutukset line: 98", true, loydetyt.get(1) == koti12); 
  } // Generated by ComTest END
}