package vakuutus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import vakuutus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.27 13:55:45 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KotivakuutusTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi90 */
  @Test
  public void testRekisteroi90() {    // Kotivakuutus: 90
    Kotivakuutus koti1 = new Kotivakuutus(); 
    assertEquals("From: Kotivakuutus line: 92", 0, koti1.getTunnusNro()); 
    koti1.rekisteroi(); 
    Kotivakuutus koti2 = new Kotivakuutus(); 
    koti2.rekisteroi(); 
    int n1 = koti1.getTunnusNro(); 
    int n2 = koti2.getTunnusNro(); 
    assertEquals("From: Kotivakuutus line: 98", n2-1, n1); 
  } // Generated by ComTest END
}