package vakuutus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import vakuutus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.13 12:42:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VakuutusTest {



  // Generated by ComTest BEGIN
  /** testLisaa41 */
  @Test
  public void testLisaa41() {    // Vakuutus: 41
    Vakuutus vakuutus = new Vakuutus(); 
    Asiakas marko1 = new Asiakas(), marko2 = new Asiakas(); 
    marko1.rekisteroi(); marko2.rekisteroi(); 
    assertEquals("From: Vakuutus line: 45", 0, vakuutus.getAsiakkaat()); 
    vakuutus.lisaa(marko1); assertEquals("From: Vakuutus line: 46", 1, vakuutus.getAsiakkaat()); 
    vakuutus.lisaa(marko2); assertEquals("From: Vakuutus line: 47", 2, vakuutus.getAsiakkaat()); 
    assertEquals("From: Vakuutus line: 48", 2, vakuutus.getAsiakkaat()); 
    assertEquals("From: Vakuutus line: 49", marko1, vakuutus.annaAsiakas(0)); 
    assertEquals("From: Vakuutus line: 50", marko2, vakuutus.annaAsiakas(1)); 
  } // Generated by ComTest END
}